version: '3'

services:
  drupal:
    image: drupal:9.3.0-apache
    ports:
      - 8080:80
    volumes:
      - ./src/web/modules:/var/www/html/modules
      - ./src/web/profiles:/var/www/html/profiles
      - ./src/web/themes:/var/www/html/themes
      - ./src/web/sites:/var/www/html/sites
    restart: always

  mysql:
    image: mysql:5.7
    ports:
      - 3037:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql:
